version: '3.7'

networks:
    dev:

services:
    db:
        image: 'mariadb:latest'
        container_name: db-container
        environment:
            MYSQL_PASSWORD: 'root'
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_DATABASE: main
        volumes:
            - db-data:/var/lib/mysql
        ports:
            - '3306:3306'
        networks:
            - dev

    adminer:
        image: adminer
        restart: always
        container_name: adminer-container
        ports:
            - '5050:8080'
        depends_on:
            - db
        networks:
            - dev

volumes:
    db-data:
        driver: local
